#!/usr/bin/env bash

set -e

arm-none-eabi-objcopy \
    -O ihex \
    target/thumbv7em-none-eabihf/release/laser-module-controller \
    target/thumbv7em-none-eabihf/release/laser-module-controller.hex

st-flash --format ihex write target/thumbv7em-none-eabihf/release/laser-module-controller.hex

exit 0
