# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required

matrix:
  include:
    # Raspberry Pi 1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_EXAMPLES=1

    # Raspberry Pi 2, 3, etc
    - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_EXAMPLES=1
    - env: TARGET=x86_64-unknown-linux-gnu DISABLE_EXAMPLES=1
    - env: TARGET=x86_64-unknown-linux-musl DISABLE_EXAMPLES=1

    # Bare metal
    - env: TARGET=thumbv6m-none-eabi DISABLE_EXAMPLES=1
    - env: TARGET=thumbv7em-none-eabi
    - env: TARGET=thumbv7em-none-eabihf
    - env: TARGET=thumbv7m-none-eabi

    - rust: nightly
      env: TARGET=thumbv7m-none-eabi

    - rust: beta
      env: TARGET=thumbv7m-none-eabi

  # Always supply a target
  exclude:
    - rust: stable
    - rust: beta
    - rust: nightly

install:
  - rustup component add rust-src
  - |
      SYSROOT=$(rustc --print sysroot)

      if [[ ! "$SYSROOT" =~ "$TARGET" ]]; then
        rustup target add $TARGET
      else
        echo "Target $TARGET is already installed"
      fi
  - source ~/.cargo/env || true

script:
  - ./build.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
